cooker_cook:
    resource: "@CookerCookingBundle/Resources/config/routing.yml"
    prefix:   /{_locale}

cooker_admin:
    resource: "@CookerAdminBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/admin

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /{_locale}/admin/controlpanel
