cooker_cook:
    resource: "@CookerCookingBundle/Resources/config/routing.yml"
    prefix:   /

cooker_cook_contact:
    path:  /contact
    defaults: { _controller: CookerCookingBundle:Cook:contact }