<?php

namespace Cooker\CookingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComentarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentarioRepository extends EntityRepository
{
	public function getComentariosForReceta($recetaId, $approved = true)
{
	$qp = $this->createQueryBuilder('c')->select('c')->where('c.receta = :receta_id')->addOrderBy('c.created')->setParameter('receta_id', $recetaId);

	if (false === is_null($approved))
		$qp->andWhere('c.approved = :approved')->setParameter('approved', $approved);

	return $qp->getQuery()->getResult();
}

}
