<?php

namespace Cooker\CookingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IngredienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredienteRepository extends EntityRepository
{
	public function getAllIngredientes($limit = null)
	{
	$qp = $this->createQueryBuilder('p')->select('p')->addOrderBy('p.nombre', 'ASC');

	if (false === is_null($limit))
		$qp->setMaxResults($limit);

	return $qp->getQuery()->getResult();
	}

	public function getIngredientesBy($recetaId)
	{
	$qp = $this->createQueryBuilder('c')->select('c')->where('c.receta = :receta_id')->addOrderBy('c.created')->setParameter('receta_id', $recetaId);

	return $qp->getQuery()->getResult();
	}

}
