<?php

namespace Cooker\CookingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecetaRepository extends EntityRepository
{
	public function getLatestRecetas($limit = null)
	{
	$qp = $this->createQueryBuilder('p')
	->select('p')
	->addOrderBy('p.date', 'DESC');

	if (false === is_null($limit))
		$qp->setMaxResults($limit);

	return $qp->getQuery()->getResult();
	}

	public function getRecetas($limit = null)
	{
	$qp = $this->createQueryBuilder('p')
	->select('p')
	->addOrderBy('p.date', 'DESC');

	if (false === is_null($limit))
		$qp->setMaxResults($limit);

	return $qp->getQuery()->getResult();
	}

	public function getRecetasBy($ingredienteId)
	{
		$qp = $this->createQueryBuilder('r')
		->innerJoin('r.ingredientes ', 'i', 'WITH', 'i.id = :ingredienteid')
		->setParameter('ingredienteid', $ingredienteId);

	  return $qp->getQuery()->getResult();
	}

	public function getRecetasOrdenadas($limit = null)
	{
	$qp = $this->createQueryBuilder('p')
	->select('p')
	->addOrderBy('p.tipo_plato', 'ASC');

	if (false === is_null($limit))
		$qp->setMaxResults($limit);

	return $qp->getQuery()->getResult();
	}

	public function getRecetasPlato($id)
	{
	$qp = $this->createQueryBuilder('p')
	->select('p')
	->where('p.tipo_plato = :id_plato')
	->setParameter('id_plato', $id);

	return $qp->getQuery()->getResult();
	}

	public function recetasRelacionadas($id)
	{
	$qp = $this->createQueryBuilder('p')
	->select('p')
	->where('p.tipo_plato = :id_plato')
	->setParameter('id_plato', $id)
	->setMaxResults(4);

	return $qp->getQuery()->getResult();
	}

}
