<?php

namespace Cooker\CookingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecetaRepository extends EntityRepository
{
	public function getLatestRecetas($limit = null)
	{
	$qp = $this->createQueryBuilder('p')->select('p')->addOrderBy('p.date', 'DESC');

	if (false === is_null($limit))
		$qp->setMaxResults($limit);

	return $qp->getQuery()->getResult();
	}

	public function getSomeRecetas($limit = null)
	{
	$qp = $this->createQueryBuilder('p')->select('p')->where('p.tipo_plato = :tipo_plato')->addOrderBy('p.date', 'DESC')->setParameter('tipo_plato', 'Primero');

	if (false === is_null($limit))
		$qp->setMaxResults($limit);

	return $qp->getQuery()->getResult();
	}

}
