blogger_blog_list:
    path: /
    defaults: { _controller: BloggerBlogBundle:Blog:list }

blogger_blog_show:
    path: /show/{id}
    defaults: { _controller: BloggerBlogBundle:Blog:show }
    
blogger_blog_contact:
    path:  /contact
    defaults: { _controller: BloggerBlogBundle:Blog:contact }

blogger_comment_create:
    path:  /comment/{receta_id}
    defaults: { _controller: BloggerBlogBundle:Comment:create }
    requirements:
        _method: POST
        post_id: \d+
